import type { Metadata } from 'next';
import { EB_Garamond, Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from '@/components/ui/sonner';
import { Providers } from '@/components/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

const eb_garamong = EB_Garamond({
  subsets: ['latin'],
  variable: '--font-heading',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={cn(inter.variable, eb_garamong.variable)}>
        <body className="min-h-[calc(100vh-1px)] bg-white text-brand-950 antialiased flex flex-col">
          <main className="relative flex flex-1 flex-col">
            <Providers>{children}</Providers>
          </main>
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}
